version: '2.0'

services:

  worker-service:
    env_file:
      - default_settings.env
      - local_settings.env
    build:
      context: .
      dockerfile: Dockerfile
    image: reprepro-management-worker-service
    volumes:
      - reprepro-management-data:/reprepro-management/
    ports:
      - 0.0.0.0:8080:8080
    user: "1024"
    restart: "no"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile-webserver
    image: reprepro-management-webserver
    volumes:
      - reprepro-management-data:/reprepro-management/
    ports:
      - 0.0.0.0:80:80
    restart: "no"

volumes:
  reprepro-management-data:
