version: '2.0'

services:

  buildenv:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-build
    volumes:
      - ..:/build/
    user: ${CURRENT_USER}
    restart: "no"

  buildenv-debian:
    build:
      context: .
      dockerfile: Dockerfile-debian
    image: node-build-debian
    volumes:
      - ..:/debian-build/build/
    user: ${CURRENT_USER}
    restart: "no"


